on: [push]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --features cli --bin apwm
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: apwm
          path: target/release/apwm

  deploy:
    environment: production
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if:
      contains('
        refs/heads/main
      ', github.ref)
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: apwm
          path: apwm
      - name: Setup ssh
        run: |
          mkdir .ssh
          chmod 700 .ssh
          echo "${{ secrets.DEPLOY_KEY }}" > .ssh/id_ed25519
          wc .ssh/id_ed25519
          wc -l .ssh/id_ed25519
          sha1sum .ssh/id_ed25519
          chmod 600 .ssh/id_ed25519
      - name: Copy
        run: scp -o StrictHostKeyChecking=no -i .ssh/id_ed25519 ./apwm/apwm ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOSTNAME }}:${{ secrets.DEPLOY_PATH }}
