[print_schema]
import_types = [ "diesel::sql_types::*", "crate::db::types::sql::*" ]

[print_schema.patches.rooms]
yaml_limit_bypass_list = { type = "Array<Int8>" }
id = { type = "SqlRoomId" }
from_template_id = { type = "Nullable<SqlRoomTemplateId>" }

[print_schema.patches.yamls]
id = { type = "SqlYamlId" }
room_id = { type = "SqlRoomId" }
apworlds = { type = "Array<Apworld>" }
bucket_id = { type = "SqlBucketId" }

[print_schema.patches.room_templates]
id = { type = "SqlRoomTemplateId" }
yaml_limit_bypass_list = { type = "Array<Int8>" }

[print_schema.patches.generations]
room_id = { type = "SqlRoomId" }
