---
trust-domain: "ap"
task-priority: low

taskgraph:
  cached-task-prefix: "ap.v2.community-ap-tools"
  repositories:
    archipelago_community_ap_tools:
      name: "community-ap-tools"

  register: eije_taskgraph:register

workers:
  aliases: {}
