on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ap-lobby
          path: target/release/ap-lobby
          retention-days: 90
